### ISSUE TITLE
Common types

### ISSUE THREAD

**Issue by nojaf** [edgarfgp/Fabulous.AST#35]
It might be interesting to introduce a set of Common types in a module somewhere.

Something like `CommonType.Int32` when you need a `Type` for `int`.

**Comment by edgarfgp** [comment]
I think this makes sense because, as of now, we only `Type.FromString("int")

**Comment by kaashyapan** [comment]
Should this be a new `CommonType` or just add static methods to the existing definition of type ?

Like so...
```fsharp
    let private mkType(typ: string) : Type =
            [ IdentifierOrDot.CreateIdent(typ) ]
            |> IdentListNode.Create
            |> Type.LongIdent

    type Type with

        static member inline Int: Type = mkType "int"
        static member inline FromString(typeName: string) : Type =
            [ IdentifierOrDot.CreateIdent(typeName) ]
            |> IdentListNode.Create
            |> Type.LongIdent

```

**Comment by edgarfgp** [comment]
@kaashyapan I think a new file with a `CommonType` module containing the basic types for now https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/basic-types, we can extend this in the future

```fsharp
module CommonType  =
    let private mkType(typ: string) : Type =
        [ IdentifierOrDot.CreateIdent(typ) ]
        |> IdentListNode.Create
        |> Type.LongIdent

    let Int32 = mkType("int")

```
