### ISSUE TITLE
Rename Widgets and Modifiers to match the Oak AST naming when possible

### ISSUE THREAD

**Issue by edgarfgp** [edgarfgp/Fabulous.AST#44]

**Comment by kaashyapan** [comment]
I think this goes against the grain - which I think is to make an api that is friendly to app devs and hide the abstruseness and complexity of the OAK/F#AST. 
I think the names should stay close to how devs think about a language construct and not to OAK which to my mind is just short form AST.
For example 'pattern' in the AST means function arguments/parameters. This should be exposed to the dev as arguments or parameters. Pattern does not make sense unless you are familiar with the AST.
Also there is the issue of naming duplications between OAK & Fabulous.Ast.

**Comment by nojaf** [comment]
I don't think other Fabulous DSLs (like for `Xamarin.Forms`) use different naming, so it should be no different for this project.

> hide the abstruseness and complexity of the OAK/F#AST.

There is nothing inherently difficult or complex about AST. To newcomers, it is nothing more than foreign. I don't believe this project should try and dumb down things for the masses. Especially when so many other projects are using this exact terminology.

> stay close to how devs think about a language construct 

That is very subjective. Every dev will have a different take on that, depending on different backgrounds. I strongly believe the discoverability of the API will suffer from this if a certain word was chosen when you are only familiar with a synonym.

In practice, most people will use the online tool anyway to reverse engineer the code snippet they are after. Reusing the same names makes a lot of sense in that scenario.

I propose the DSL should offer two flavours: one that closely matches the Oak model it tries to represent. And a handful of higher abstractions that can shortcut some of the code you need for certain constructs.
